In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
X = pd.read_csv('train_dummies.csv')
y = pd.read_csv('train.csv')['SalePrice']

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
from sklearn.tree import DecisionTreeRegressor

In [31]:
model = DecisionTreeRegressor(random_state=101)

In [32]:
model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=101)

In [33]:
dc_preds = model.predict(X_test)

In [34]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [35]:
mae = mean_absolute_error(y_test, dc_preds)
mae

26210.534246575342

In [36]:
rmse = np.sqrt(mean_squared_error(y_test, dc_preds))
rmse

41893.77221319586

In [37]:
final_test = pd.read_csv('test_dummies.csv')
final_test = scaler.transform(final_test)

In [38]:
final_preds = model.predict(final_test)

In [39]:
final_preds

array([125000., 157000., 244000., ..., 170000., 105000., 239000.])

In [40]:
submission = pd.concat([pd.read_csv('test.csv')['Id'],pd.DataFrame(final_preds)], axis=1)
submission.columns = ['Id', 'SalePrice']

In [41]:
submission.to_csv('DTsubmission.csv', index=False)

In [42]:
from sklearn.ensemble import RandomForestRegressor

In [43]:
rf_model = RandomForestRegressor(random_state=101)

In [44]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=101)

In [45]:
rf_preds = rf_model.predict(X_test)

In [46]:
mae = mean_absolute_error(y_test, rf_preds)
mae

18125.05694063927

In [47]:
rmse = np.sqrt(mean_squared_error(y_test, rf_preds))
rmse

31377.891837036103

In [48]:
final_rf_preds = rf_model.predict(final_test)

In [49]:
final_rf_preds

array([125076.58, 159137.36, 173013.02, ..., 156265.61, 118075.82,
       224687.49])

In [50]:
submission = pd.concat([pd.read_csv('test.csv')['Id'],pd.DataFrame(final_rf_preds)], axis=1)
submission.columns = ['Id', 'SalePrice']

In [51]:
submission.to_csv('RFsubmission.csv', index=False)

In [52]:
# Gradient Boost Regressor

In [55]:
from sklearn.ensemble import GradientBoostingRegressor, AdaBoostRegressor
gb_model = GradientBoostingRegressor(random_state=101)

In [56]:
gb_model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=101)

In [57]:
gb_preds = gb_model.predict(X_test)

In [58]:
mae = mean_absolute_error(y_test, gb_preds)
mae

15911.296644155162

In [59]:
rmse = np.sqrt(mean_squared_error(y_test, gb_preds))
rmse

25210.512806014012

In [60]:
final_gb_preds = gb_model.predict(final_test)

In [61]:
final_gb_preds

array([123725.8807463 , 169417.55715804, 172964.10941208, ...,
       163193.50212099, 124583.36899196, 236961.18592733])

In [62]:
submission = pd.concat([pd.read_csv('test.csv')['Id'],pd.DataFrame(final_gb_preds)], axis=1)
submission.columns = ['Id', 'SalePrice']

In [63]:
submission.to_csv('GBsubmission.csv', index=False)

In [67]:
ada_model = AdaBoostRegressor(random_state=101)
ada_model.fit(X_train, y_train)
ada_preds = ada_model.predict(X_test)

In [68]:
mae = mean_absolute_error(y_test, ada_preds)
mae

24094.587333382326

In [69]:
rmse = np.sqrt(mean_squared_error(y_test, ada_preds))
rmse

35821.59520120602

In [70]:
final_ada_preds = ada_model.predict(final_test)

In [71]:
submission = pd.concat([pd.read_csv('test.csv')['Id'],pd.DataFrame(final_ada_preds)], axis=1)
submission.columns = ['Id', 'SalePrice']

In [72]:
submission.to_csv('ADAsubmission.csv', index=False)